version: '2'
services:

  ## Router
  router:
    image: mongo:4.0
    container_name: router
    command: mongos --port 27017 --configdb rs-config-server/config-server:27017 --bind_ip_all
    ports:
      - 27117:27017
    volumes:
      - ./scripts:/scripts

  ## Config Server
  config-server:
    image: mongo:4.0
    container_name: config-server
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
    ports:
      - 27118:27017
    links:
      - shard-a

  ## Shards
  shard-x:
    image: mongo:4.0
    container_name: shard-x
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27119:27017
    links:
      - shard-a
      - shard-b
  shard-a:
    image: mongo:4.0
    container_name: shard-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27120:27017
  shard-b:
    image: mongo:4.0
    container_name: shard-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27121:27017

